services:
  wordpress_install:
    image: wordpress:cli
    environment:
      WORDPRESS_DB_HOST: ${NAME}-db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    command: >
      /bin/sh -c '
      wp core install --path="/var/www/html" --url="https://wp-dev.ucsc" --title="Local Wordpress with HTTPS & LDAP" --admin_user=admin --admin_password=password --admin_email=raknight@ucsc.edu;
      wp theme activate ucsc-2022;
      wp plugin activate ucsc-gutenberg-blocks;
      wp plugin activate ucsc-custom-functionality;
      wp rewrite structure '/%year%/%monthnum%/%postname%/';
      '
    volumes:
      - ./public/:/var/www/html
    networks:
      - wpsite
    platform: linux/amd64
  theme_composer_install:
    image: composer/composer
    volumes:
      - "./public/:/var/www/html"
    working_dir: /var/www/html/wp-content/themes/ucsc-2022
    command: install
    platform: linux/amd64
  theme_npm_install:
    image: node:16.18.0-alpine3.15
    volumes:
      - "./public/:/var/www/html"
    working_dir: /var/www/html/wp-content/themes/ucsc-2022
    command: npm install
    platform: linux/amd64
  plugin_npm_install:
    image: node:16.18.0-alpine3.15
    volumes:
      - "./public/:/var/www/html"
    working_dir: /var/www/html/wp-content/plugins/ucsc-gutenberg-blocks
    command: npm install
    platform: linux/amd64

networks:
  wpsite: null
