version: '3.9'

services:
  theme_composer:
    image: composer/composer
    volumes:
      - "./public/:/var/www/html"
    working_dir: /var/www/html/wp-content/themes/ucsc-2022
    command: install
  theme_npm_install:
    image: node:16.18.0-alpine3.15
    volumes:
      - "./public/:/var/www/html"
    working_dir: /var/www/html/wp-content/themes/ucsc-2022
    command: npm install
  plugin_npm_install:
    image: node:16.18.0-alpine3.15
    volumes:
      - "./public/:/var/www/html"
    working_dir: /var/www/html/wp-content/plugins/ucsc-gutenberg-blocks
    command: npm install
  wp_activate_plugin_and_theme:
    depends_on:
      - theme_composer
      - theme_npm_install
      - plugin_npm_install
    image: wordpress:cli
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    user: xfs
    command: >
      /bin/sh -c '
      wp theme activate ucsc-2022;
      wp plugin activate ucsc-gutenberg-blocks;
      '
    volumes:
      - ./public/:/var/www/html
    networks:
      - wpsite
  theme_npm_start:
    depends_on:
      - wp_activate_plugin_and_theme
    image: node:16.18.0-alpine3.15
    volumes:
      - "./public/:/var/www/html"
    working_dir: /var/www/html/wp-content/themes/ucsc-2022
    command: npm run start
  plugin_npm_start:
    depends_on:
      - wp_activate_plugin_and_theme
    image: node:16.18.0-alpine3.15
    volumes:
      - "./public/:/var/www/html"
    working_dir: /var/www/html/wp-content/plugins/ucsc-gutenberg-blocks
    command: npm run start

networks:
  wpsite: null
