version: '3.9'

services:
  proxy:
    image: nginx:1.19.10-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/certs:/etc/nginx/certs
    networks:
      - wpsite
    depends_on:
      - wordpress
  wordpress:
    build: .
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_CONFIG_EXTRA: define('WP_ALLOW_MULTISITE', true);
      DOCKER_DEV: docker_dev
    volumes: [ './public/:/var/www/html' ]
    hostname: wp-dev.ucsc
    labels:
      com.ucsc.expose.domain: "wp-dev.ucsc"
      com.ucsc.expose.domainIsHost: "true"
      com.ucsc.expose.subdomainHosts: "site1 site2 site3"
    networks:
      wpsite:
        aliases:
          - wp-dev.ucsc
    depends_on:
      - db
  db:
    image: mysql:5.7.34
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - wpsite

networks:
  wpsite: null
volumes:
  wordpress: null
  db: null
