services:
  theme_npm_start:
    image: node:16.18.0-alpine3.15
    volumes:
      - "./public/:/var/www/html"
    working_dir: /var/www/html/wp-content/themes/ucsc-2022
    command: npm run start
    networks:
      - wpsite
    platform: linux/amd64
  plugin_npm_start:
    image: node:16.18.0-alpine3.15
    volumes:
      - "./public/:/var/www/html"
    working_dir: /var/www/html/wp-content/plugins/ucsc-gutenberg-blocks
    command: npm run start
    networks:
      - wpsite
    platform: linux/amd64

networks:
  wpsite: null
