version: '3.9'

services:
  proxy:
    image: nginx:1.19.10-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/certs:/etc/nginx/certs
    networks:
      - wpsite
    depends_on:
      - wordpress
  wordpress:
    build: .
    restart: always
    user: xfs
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_CONFIG_EXTRA: define('WP_ALLOW_MULTISITE', true);
    volumes: [ './public/:/var/www/html' ]
    hostname: ucsc-gutenberg-blocks.local
    labels:
      com.ucsc.expose.domain: "ucsc-gutenberg-blocks.local"
      com.ucsc.expose.domainIsHost: "true"
      com.ucsc.expose.subdomainHosts: "site1 site2 site3"
    networks:
      wpsite:
        aliases:
          - ucsc-gutenberg-blocks.local
    depends_on:
      - db
  db:
    image: mysql:5.7.34
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - wpsite
  wordpresscli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    user: xfs
    command: >
      /bin/sh -c '
      sleep 15;
      wp core install --path="/var/www/html" --url="https://ucsc-gutenberg-blocks.local" --title="Local Wordpress W/ HTTPS & LDAP" --admin_user=user --admin_password=password --admin_email=sammytheslug@ucsc.edu
      '
    volumes:
      - ./public/:/var/www/html
    networks:
      - wpsite

networks:
  wpsite: null
volumes:
  wordpress: null
  db: null
