version: '3.9'

services:
  wordpress_install:
    image: wordpress:cli
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    command: >
      /bin/sh -c '
      wp core install --path="/var/www/html" --url="https://wp-dev.ucsc" --title="Local Wordpress W/ HTTPS & LDAP" --admin_user=user --admin_password=password --admin_email=sammytheslug@ucsc.edu;
      wp theme activate ucsc-2022;
      wp plugin activate ucsc-gutenberg-blocks;
      '
    volumes:
      - ./public/:/var/www/html
    networks:
      - wpsite
  theme_composer:
    image: composer/composer
    volumes:
      - "./public/:/var/www/html"
    working_dir: /var/www/html/wp-content/themes/ucsc-2022
    command: install
  theme_npm_install:
    image: node:16.18.0-alpine3.15
    volumes:
      - "./public/:/var/www/html"
    working_dir: /var/www/html/wp-content/themes/ucsc-2022
    command: npm install
  plugin_npm_install:
    image: node:16.18.0-alpine3.15
    volumes:
      - "./public/:/var/www/html"
    working_dir: /var/www/html/wp-content/plugins/ucsc-gutenberg-blocks
    command: npm install

networks:
  wpsite: null
